// <auto-generated />
// Generated from Worldbuilding/地图配置/战斗地图/*.occ-map.json by Tools/BattleMapEditor/map-build.mjs.
using System;
using System.Collections.Generic;
using System.Linq;

namespace OCC.Combat
{
    public static class GeneratedBattleMapCatalog
    {
        public static readonly IReadOnlyList<FirstRegionLevelDefinition> FirstRunLevels = new[]
        {
            new FirstRegionLevelDefinition("rain_lantern_court", "普通战斗 01 · 雨后灯庭", "让寻迹兽失去行动能力，并让高年级火矢生认输。", CombatObjectiveType.Elimination, 1,
                new GridPosition(1, 4), FirstRegionFloorTheme.Courtyard, false, false, Array.Empty<string>(),
                new[]
                {
                    new LevelEnemyPlacement("tether_hound", 4, 3),
                    new LevelEnemyPlacement("pyromancer", 5, 0)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(1, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 4, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("雨后石庭、短浅水横带、双列灯藤与西侧安全入口",
                    "寻迹兽封住近侧，火矢生沿干地与藤列形成公开射线。", "可入藤延迟搜查、借浅水灭火，或沿西侧掩体先处理寻迹兽。"),
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("first_battle_greenhouse_collection_room", "普通战斗 02 · 温室藏品间", "击倒替身偶与侧锋生；中央备件箱可搜刮苗床回流芯。", CombatObjectiveType.Elimination, 2,
                new GridPosition(1, 3), FirstRegionFloorTheme.Courtyard, false, false, new[] { "rain_lantern_court" },
                new[]
                {
                    new LevelEnemyPlacement("raider", 6, 1),
                    new LevelEnemyPlacement("sigil_mauler", 6, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.LootChest, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 1, LevelTerrainKind.AetherCrystal, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.AetherCrystal, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("中央藤圈宝箱、东侧双晶簇、南侧普通路线",
                    "侧锋与替身偶分守两枚晶簇，藤圈遮断中央攻击线。", "可跃进入藤搜刮、等待敌人贴晶后引爆，或不搜刮不引爆、以常规移动穿过南侧灯藤。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("first_b3_rain_prism_court", "普通战斗 03 · 雨痕晶庭", "击倒替身偶与火矢生；可破坏封门晶簇搜刮学院储能芯。", CombatObjectiveType.Elimination, 3,
                new GridPosition(1, 2), FirstRegionFloorTheme.Courtyard, false, false, new[] { "first_battle_greenhouse_collection_room" },
                new[]
                {
                    new LevelEnemyPlacement("sigil_mauler", 4, 2),
                    new LevelEnemyPlacement("pyromancer", 5, 0)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.AetherCrystal, 0),
                    new LevelTerrainPlacement(6, 2, LevelTerrainKind.LootChest, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(7, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.LightCover, 0)
                },
                new LevelSpaceContract("纵向冷却沟、封门晶簇与北侧普通路线",
                    "火矢生从干地施加燃烧，封门晶簇与永久重物块围出器材匣。", "可破晶开匣并爆伤替身偶、退入浅水熄火，或放弃搜刮走北侧普通路线。"),
                width: 8, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("first_elite_three_material_pressure", "精英战斗 01 · 三材承压场", "击倒楔角。", CombatObjectiveType.Elimination, 4,
                new GridPosition(1, 3), FirstRegionFloorTheme.Courtyard, true, false, new[] { "first_b3_rain_prism_court" },
                new[]
                {
                    new LevelEnemyPlacement("breach_ram", 6, 3)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 3, LevelTerrainKind.PressureCrystal, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("冷却沟、双灯藤带、中央稳压晶簇与两侧干路",
                    "楔角公开锁定冲压线，并会撞击晶簇、单位或灯藤。", "可诱导撞晶、藏入灯藤、用浅水缩短冲压，或走南侧干路等待卸压。"),
                width: 8, height: 6, blockedPositions: Array.Empty<GridPosition>())
        };

        public static readonly IReadOnlyList<FirstRegionLevelDefinition> CoreLevels = new[]
        {
            new FirstRegionLevelDefinition("rail_patrol", "普通战斗 04 · 石路巡哨", "清除石路巡哨队", CombatObjectiveType.Elimination, 1,
                new GridPosition(2, 4), FirstRegionFloorTheme.StoneRoad, false, false, Array.Empty<string>(),
                new[]
                {
                    new LevelEnemyPlacement("shieldguard", 2, 2),
                    new LevelEnemyPlacement("pyromancer", 0, 0),
                    new LevelEnemyPlacement("raider", 5, 0)
                },
                new[]
                {
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(0, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 3, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("短石路交叉线与底边门墩",
                    "压中会进入两翼交叉影响区。", "左右翼均可回到底边换线，中央盾位不封死两侧。"),
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("depot_wreck", "普通战斗 05 · 废弃驿站", "清除占据驿站的敌人", CombatObjectiveType.Elimination, 1,
                new GridPosition(2, 2), FirstRegionFloorTheme.Ruins, false, false, Array.Empty<string>(),
                new[]
                {
                    new LevelEnemyPlacement("tether_hound", 0, 0),
                    new LevelEnemyPlacement("sigil_mauler", 5, 4),
                    new LevelEnemyPlacement("stone_snare", 5, 0)
                },
                new[]
                {
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("三口收束的小驿站废墟",
                    "三股追击从不同方向抵达，中线停留会叠加控制。", "上下宽口都能拆开三名敌人的接触节奏。"),
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("relay_raid", "普通战斗 06 · 野外导能柱", "破坏被敌军占用的导能柱", CombatObjectiveType.Destruction, 2,
                new GridPosition(4, 0), FirstRegionFloorTheme.AetherMarked, false, false, new[] { "rail_patrol" },
                new[]
                {
                    new LevelEnemyPlacement("raider", 4, 2),
                    new LevelEnemyPlacement("rune_arbalist", 5, 4),
                    new LevelEnemyPlacement("tether_hound", 1, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(0, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.AetherObjective, 0)
                },
                new LevelSpaceContract("偏心目标与折线掩体",
                    "直切目标会进入背弩生公开射线。", "可先压制背弩生，也可由下侧掩体接近目标。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("signal_hub", "普通战斗 07 · 传讯石庭", "清除传讯石庭守军", CombatObjectiveType.Elimination, 2,
                new GridPosition(0, 4), FirstRegionFloorTheme.Courtyard, false, false, new[] { "depot_wreck" },
                new[]
                {
                    new LevelEnemyPlacement("barrier_mender", 4, 1),
                    new LevelEnemyPlacement("lantern_revealer", 1, 1),
                    new LevelEnemyPlacement("shieldguard", 4, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("三角维护网与北侧石台",
                    "切任一支援点都会留下另外两条公开维护关系。", "外围保持连通，可在看见显影与护障意图后换边。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("gatehouse", "普通战斗 08 · 石闸关口", "夺取石闸关口", CombatObjectiveType.Elimination, 3,
                new GridPosition(3, 3), FirstRegionFloorTheme.Courtyard, false, false, new[] { "signal_hub", "relay_raid" },
                new[]
                {
                    new LevelEnemyPlacement("shieldguard", 0, 3),
                    new LevelEnemyPlacement("sigil_mauler", 5, 1),
                    new LevelEnemyPlacement("rune_arbalist", 5, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 4, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("双向门厅与上下门楣",
                    "两条门道分别暴露于近战截击与背弩射线。", "两路均保持两格宽，可在门厅中央改变方向。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("transmission_tower", "普通战斗 09 · 传讯塔楼", "破坏塔楼内的敌方导能柱", CombatObjectiveType.Destruction, 3,
                new GridPosition(0, 2), FirstRegionFloorTheme.AetherMarked, false, false, new[] { "signal_hub" },
                new[]
                {
                    new LevelEnemyPlacement("pyromancer", 5, 1),
                    new LevelEnemyPlacement("stone_snare", 5, 4),
                    new LevelEnemyPlacement("lantern_revealer", 1, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.AetherObjective, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("中央装置与三个短扇区",
                    "接近中心只能遮蔽一部分远程压力。", "目标破坏即胜；可快拆或先从左上处理显影。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("elite_foundry", "精英战斗 02 · 刻阵工坊", "摧毁工坊内的敌方导能柱", CombatObjectiveType.Destruction, 3,
                new GridPosition(2, 5), FirstRegionFloorTheme.Ruins, true, false, new[] { "signal_hub" },
                new[]
                {
                    new LevelEnemyPlacement("elite_vanguard", 2, 2),
                    new LevelEnemyPlacement("barrier_mender", 0, 0),
                    new LevelEnemyPlacement("sigil_mauler", 0, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 0, LevelTerrainKind.AetherObjective, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("编织狭口与双短路",
                    "左路承受破势，右路更快接近目标但会被教官横移拦截。", "两路在中部连通，单个敌人无法封死双路。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("core_approach", "精英战斗 03 · 塔前石庭", "清除古塔前庭守军", CombatObjectiveType.Elimination, 4,
                new GridPosition(0, 4), FirstRegionFloorTheme.Courtyard, true, false, new[] { "transmission_tower", "elite_foundry" },
                new[]
                {
                    new LevelEnemyPlacement("elite_vanguard", 2, 3),
                    new LevelEnemyPlacement("rune_arbalist", 5, 1),
                    new LevelEnemyPlacement("stone_snare", 5, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(0, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(5, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("对角封线与中央缺口",
                    "背弩与约束控制相反对角，教官惩罚直穿。", "外围路线较慢，中心两侧缺口允许在意图公开后换线。"),
                width: 6, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("core_finale", "Boss战斗 01 · 古塔核心", "击败拦在必经之路上的塔之守卫", CombatObjectiveType.Elimination, 5,
                new GridPosition(0, 3), FirstRegionFloorTheme.AetherMarked, false, true, new[] { "core_approach" },
                new[]
                {
                    new LevelEnemyPlacement("core_overseer", 4, 3)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(6, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(6, 1, LevelTerrainKind.TowerMechanism, 1),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.TowerMechanism, 2),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.TowerMechanism, 3),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(0, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(7, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("中心核心、三道机关与四角塔墙",
                    "核心居中，三组机关按阶段逐组放行。", "机关耐久与阶段公开，可先拆已放行机关切断对应加成。"),
                width: 8, height: 6, blockedPositions: Array.Empty<GridPosition>())
        };

        public static readonly IReadOnlyList<FirstRegionLevelDefinition> EliteLevels = new[]
        {
            new FirstRegionLevelDefinition("calibration_lockdown", "精英战斗 04 · 失控校准室封锁", "击倒试制员、背弩生与拴索助教。", CombatObjectiveType.Elimination, 3,
                new GridPosition(0, 3), FirstRegionFloorTheme.Ruins, true, false, new[] { "rail_patrol", "depot_wreck" },
                new[]
                {
                    new LevelEnemyPlacement("prototype_hand", 4, 3),
                    new LevelEnemyPlacement("rune_arbalist", 6, 1),
                    new LevelEnemyPlacement("stone_snare", 6, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.WardGenerator, 0, 0, 16),
                    new LevelTerrainPlacement(1, 4, LevelTerrainKind.OverloadDevice, 0, 0, 16),
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("设备间短走廊、冷却沟与双装置区",
                    "试制件逐段堵路，背弩射线覆盖主廊。", "可先拆试制件、反用过载区，或从外侧短路绕行。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("cliff_relay_survey", "精英战斗 05 · 断崖导能柱考察", "击倒老寻、灯台值守与补盾助教。", CombatObjectiveType.Elimination, 3,
                new GridPosition(0, 4), FirstRegionFloorTheme.Ruins, true, false, new[] { "rail_patrol", "depot_wreck" },
                new[]
                {
                    new LevelEnemyPlacement("elder_tracker_hound", 4, 4),
                    new LevelEnemyPlacement("signal_keeper", 6, 3),
                    new LevelEnemyPlacement("barrier_mender", 6, 1)
                },
                new[]
                {
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(2, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 1, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.LampVine, 0),
                    new LevelTerrainPlacement(5, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("断崖坡面、积水带、灯藤暗段与基座",
                    "光柱封住中廊，老寻沿痕提速。", "走积水清痕，或借重物块与基座留下的暗段换线。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("sealed_vault_certification", "精英战斗 06 · 封存库权限核验", "击倒老库管、提灯巡查与替身偶。", CombatObjectiveType.Elimination, 3,
                new GridPosition(0, 4), FirstRegionFloorTheme.AetherMarked, true, false, new[] { "relay_raid", "signal_hub" },
                new[]
                {
                    new LevelEnemyPlacement("legacy_storekeeper", 5, 3),
                    new LevelEnemyPlacement("lantern_revealer", 6, 1),
                    new LevelEnemyPlacement("sigil_mauler", 4, 4)
                },
                new[]
                {
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(6, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 3, LevelTerrainKind.WardGenerator, 0, 0, 16),
                    new LevelTerrainPlacement(1, 2, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(0, 1, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(4, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("货架短墙与消防积水构成的库房通道",
                    "老库管会退掉新场地，提灯巡查沿直线施加破势。", "利用货架短墙切断旧脉冲，或抢在登记生效前从积水侧推进。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("library_discipline", "精英战斗 07 · 图书馆纠察", "击倒小铃、补盾助教与替身偶。", CombatObjectiveType.Elimination, 3,
                new GridPosition(1, 3), FirstRegionFloorTheme.Courtyard, true, false, new[] { "rail_patrol", "relay_raid" },
                new[]
                {
                    new LevelEnemyPlacement("wind_librarian", 6, 1),
                    new LevelEnemyPlacement("barrier_mender", 6, 4),
                    new LevelEnemyPlacement("sigil_mauler", 6, 3)
                },
                new[]
                {
                    new LevelTerrainPlacement(0, 3, LevelTerrainKind.LightCover, 0),
                    new LevelTerrainPlacement(2, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(1, 4, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(5, 1, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(5, 4, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(5, 3, LevelTerrainKind.BindingMark, 0, 3),
                    new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(3, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("书架双廊、阅览桌与散页堆",
                    "页幕和书架会截断攻击线，补盾助教依附长桌。", "烧掉或打湿散页，再从另一条走廊压上。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>()),
            new FirstRegionLevelDefinition("outer_ring_clearance", "精英战斗 08 · 高塔外环清障", "击倒划线教官、提灯巡查与背弩生。", CombatObjectiveType.Elimination, 3,
                new GridPosition(0, 3), FirstRegionFloorTheme.AetherMarked, true, false, new[] { "relay_raid", "signal_hub" },
                new[]
                {
                    new LevelEnemyPlacement("elite_vanguard", 4, 3),
                    new LevelEnemyPlacement("lantern_revealer", 6, 4),
                    new LevelEnemyPlacement("rune_arbalist", 6, 1)
                },
                new[]
                {
                    new LevelTerrainPlacement(2, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(3, 4, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(5, 2, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(4, 4, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(4, 1, LevelTerrainKind.LoosePaper, 0),
                    new LevelTerrainPlacement(2, 4, LevelTerrainKind.Water, 0),
                    new LevelTerrainPlacement(3, 3, LevelTerrainKind.HeavyCover, 0),
                    new LevelTerrainPlacement(1, 1, LevelTerrainKind.WardGenerator, 0, 0, 16),
                    new LevelTerrainPlacement(1, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(5, 5, LevelTerrainKind.PermanentWall, 0),
                    new LevelTerrainPlacement(6, 5, LevelTerrainKind.PermanentWall, 0)
                },
                new LevelSpaceContract("外环直廊、中央物块堆与两处重掩体",
                    "背弩重矢与显影沿同一廊道叠加。", "借永久重物块遮断直线，或先拆重掩体再压上。"),
                width: 7, height: 6, blockedPositions: Array.Empty<GridPosition>())
        };

        private static readonly IReadOnlyDictionary<string, FirstRegionLevelDefinition> ById =
            FirstRunLevels.Concat(CoreLevels).Concat(EliteLevels).ToDictionary(level => level.Id, StringComparer.Ordinal);

        private static readonly IReadOnlyDictionary<string, RogueliteEncounterLayout> WeakLayouts =
            new Dictionary<string, RogueliteEncounterLayout>(StringComparer.Ordinal)
            {
            ["W1"] = new RogueliteEncounterLayout("W1", new GridPosition(2, 4),
                new[] { new GridPosition(1, 0), new GridPosition(4, 0) },
                new[] { new LevelTerrainPlacement(1, 1, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(4, 1, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(2, 2, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(0, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(5, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(2, 0, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(3, 0, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(3, 3, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(3, 2, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(2, 3, LevelTerrainKind.PermanentWall, 0) },
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            ["W2"] = new RogueliteEncounterLayout("W2", new GridPosition(1, 4),
                new[] { new GridPosition(5, 0), new GridPosition(5, 3) },
                new[] { new LevelTerrainPlacement(3, 0, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(4, 1, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(1, 2, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(2, 2, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(1, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(3, 3, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(3, 4, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(0, 1, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0) },
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            ["W3"] = new RogueliteEncounterLayout("W3", new GridPosition(2, 4),
                new[] { new GridPosition(1, 0), new GridPosition(4, 0) },
                new[] { new LevelTerrainPlacement(2, 1, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(3, 1, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(1, 2, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(4, 2, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(2, 3, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(3, 3, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(0, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(5, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0) },
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>()),
            ["W4"] = new RogueliteEncounterLayout("W4", new GridPosition(0, 4),
                new[] { new GridPosition(4, 0), new GridPosition(5, 3) },
                new[] { new LevelTerrainPlacement(4, 1, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(1, 1, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(2, 1, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(4, 2, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(2, 3, LevelTerrainKind.LightCover, 0), new LevelTerrainPlacement(4, 3, LevelTerrainKind.HeavyCover, 0), new LevelTerrainPlacement(0, 0, LevelTerrainKind.PermanentWall, 0), new LevelTerrainPlacement(5, 0, LevelTerrainKind.PermanentWall, 0) },
                width: 6, height: 5, blockedPositions: Array.Empty<GridPosition>())
            };

        public static FirstRegionLevelDefinition For(string id) => ById[id];
        public static RogueliteEncounterLayout WeakLayout(string signature) => WeakLayouts[signature];
    }
}
