#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];M=ROOT/"Worldbuilding/05_美术与音频/正式美术生产/M-A31";A=ROOT/"UnityProject/Artifacts/UiChapterMarkers6"
ASSETS={"teaching_chalk_clip":"a compact forged-iron paper clip gripping one tiny blank warm-paper corner and one short ivory chalk stub","workshop_caliper_clip":"a compact forged-iron document clip on a tiny worn wooden foot, with one simplified caliper jaw shape integrated into the clip","infirmary_bandage_clip":"a compact off-white enamel document clip holding one folded muted grey-green bandage strip","field_leaf_clip":"a compact worn wooden field-note clip with one natural-fibre cord loop securing a single pressed olive leaf","sealed_red_clip":"a compact dark forged-iron document clip gripping one short restrained sealed-red cloth binding strip","reward_brass_tag":"a compact worn wooden claim clip holding one small blank oxidized-brass inventory tag, no writing"}
def main():
 (M/"manifests").mkdir(parents=True,exist_ok=True);cat=[]
 for stem,subject in ASSETS.items():
  (A/stem).mkdir(parents=True,exist_ok=True);prompt=f"Use case: stylized-concept\nAsset type: independent non-interactive OCC chapter corner marker source; final native 32x32 pixel canvas\nPrimary request: {subject}\nScene/backdrop: genuinely transparent background, isolated single compact object only\nStyle/medium: coarse hand-clustered pixel art, hard near-black stair-step outline, dominant silhouette readable at 1x, two structural partitions, 5 to 10 discrete flat colors\nLighting/mood: fixed upper-left light, one connected highlight cluster and one hard shadow mass, no glow\nComposition/framing: centered front three-quarter view, compact 20 to 27 pixel subject, clean transparent border on every side, original orientation\nConstraints: one physical clip marker, actual transparency, no interface, no text, no letters, no numbers, no emblem, no symbol, no badge plate, no button, no complete card\nAvoid: blue crystal, cyan energy, magic glow, neon, hologram, steampunk gears or pipes, medieval scroll curls, wax seals, gradients, bloom, soft focus, anti-aliasing, watermark";cat.append({"stem":stem,"subject":subject,"prompt":prompt});m={"schema":"occ-art-manifest-v1","contract_version":1,"asset_id":f"ui.marker.{stem}","role":"ui_chapter_marker_32","status":"QA_PENDING","provenance":{"source_channel":"codex_builtin_imagegen","source_descriptor":"Independent single transparent chapter marker source; no board slicing","source_path":f"UnityProject/Artifacts/UiChapterMarkers6/{stem}/source.png","source_sha256":"PENDING_GENERATION"},"delivery":{"output_path":f"UnityProject/Assets/Game/Resources/Art/ValidationUIChapterMarkers/{stem}.png","output_sha256":"PENDING_NORMALIZATION","native_output_path":None,"logical_cells":None,"palette_max":10,"required_color_families":[]},"application":{"runtime_draw_rect":"title-adjacent non-interactive marker at native 32x32, nearest-neighbour 2x or 4x","default_integer_scale":4,"minimum_integer_scale":2},"evidence":{"one_x":f"UnityProject/Artifacts/UiChapterMarkers6/{stem}/1x.png","four_x":f"UnityProject/Artifacts/UiChapterMarkers6/{stem}/4x.png","grayscale":f"UnityProject/Artifacts/UiChapterMarkers6/{stem}/grayscale.png","checker":f"UnityProject/Artifacts/UiChapterMarkers6/{stem}/checker.png","application_contact":"UnityProject/Artifacts/UiChapterMarkers6/contacts/PENDING.png"},"human_review":{"overall":"PENDING","reviewer":"","date":"","silhouette":"PENDING","material":"PENDING","perspective":"PENDING","style":"PENDING","application":"PENDING","notes":subject},"unity_import":None};(M/"manifests"/f"marker_{stem}.occ-art-manifest-v1.json").write_text(json.dumps(m,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 (M/"ui_chapter_markers_6_catalog.json").write_text(json.dumps(cat,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps({"status":"PASS","prepared":6}))
if __name__=="__main__":main()
